- R/axes.R
- R/save_e61.R
- R/scales.R
- R/theme_e61.R
- tests/testthat/test-save_e61.R
> Add messages that tell users to use the theme61 component functions when they have not been used

- R/plot_label.R
- vignettes/graph-standards.rmd
> Tidying up a few issues post merge

- R/aes_y_lims.R
- tests/testthat/test-auto-y-axis-scaling.R
> Fixed issue with geom_ribbon and anchoring to 0

- DESCRIPTION
> Fixing missing dependency R.devices

- DESCRIPTION
- R/mpanel_e61.R
- R/save_e61.R
> fixing a few minor bugs

- R/mpanel_e61.R
> Updated mpanel title sizing to allow it to extend across the whole chart

- R/aes_labs.R
- R/mpanel_e61.R
- R/save_e61.R
- man/save_mpanel_e61.Rd
> Bug fixing

- R/aes_labs.R
- R/mpanel_e61.R
> Adding safe guards to the save_mpanel function

- R/aes_labs.R
- R/mpanel_e61.R
- R/save_e61.R
- R/utils-plot-dims.R
> Fixing bug in y-axis label scaling

- R/mpanel_e61.R
> Adjusting footnote and chart spacing for mpanel plots

- R/mpanel_e61.R
> Added warning messages to save_mpanel_e61

- R/mpanel_e61.R
- R/save_e61.R
> Updates to fix issues with autoscaler and inconsistent use of save_e61()

- R/aes_labs.R
- R/save_e61.R
> Fixing issues with footnotes not showing when no sources are provided

- R/aes_labs.R
- R/ggplot2-wrappers.R
- R/mpanel_e61.R
- R/save_e61.R
> Fixing issues with integer variables used for y-aesthetic

- R/ggplot2-wrappers.R
> Small tweaks to recent bug fixes that weren't quite complete

- R/save_e61.R
> Jb bug fixing

- R/theme_e61.R
> Fixing small issue with the spatial theme

- R/aes_y_lims.R
- R/mpanel_e61.R
- R/save_e61.R
…fined in the main ggplot call
> Added ability to scale y-axis nicely even when y variables are not defined in the main ggplot call

- R/ggplot2-wrappers.R
> Fix issue with multi-class vectors

- R/mpanel_e61.R
- R/save_e61.R
> format was broken in mpanels; some post-save functionality is missing

- R/aes_labs.R
- R/mpanel_e61.R
- R/plot_label.R
> Fixed sizing of mplot_labels in mpanel_e61

- R/aes_labs.R
- R/mpanel_e61.R
- R/plot_label.R
- R/save_e61.R
Updated mplot label auto sizing and improved the performance of the automatic y-axis label positioning
> Jb updates

- R/theme_e61.R
- man/theme_e61_spatial.Rd
> Fixing issue with theme_e61_spatial's aspect ratio

- R/save-helpers.R
- R/save_e61.R
- R/save_multi.R
- R/save_single.R
- man/save_e61.Rd
- tests/testthat/test-save_e61.R
> Kill png and other small things

- R/save_e61.R
- tests/testthat/test-save_e61.R
> whoops, this didnt work when you save directly in the home directory

- R/save_e61.R
> error only exists in prod..

- R/save_e61.R
> Fix angry msgs

- DESCRIPTION
- R/check_pkg_ver.R
- R/zzz.R
> adds a version checker that runs on load to prompt users if they are out-of-date

- R/save_e61.R
- man/save_e61.Rd
- tests/testthat/test-save_e61.R
> Tweaks to the advisory messages

- DESCRIPTION
> Removing e61 chart maker dependency

- R/theme_e61.R
- man/theme_e61.Rd
> removing keep legend argument

- tests/testthat/test-save_e61.R
> Break more graphs

- R/axes.R
> issue with breaks on sec_rescale

- R/save_single.R
- R/theme_e61.R
- tests/testthat/test-auto-y-axis-scaling.R
> Fixing the spatial theme

- R/save_single.R
> Adding back in label adjustment to spatial charts

- R/aes-y-lims.R
> removing pointless error message

- R/check_pkg_ver.R
> Workaround for GH API error

- R/aes-y-lims.R
> Fixing auto y-scale issue

- R/zzz.R
> Change the default colours from black

- R/e61_map.R
- man/add_map_e61.Rd
> Minor fixes to map funcs

- R/ggplot2-wrappers.R
> catch NAs and NaNs before they are passed through

- R/save_e61.R
- R/save_multi.R
- R/save_single.R
- README.md
- man/save_e61.Rd
> Jb changes

- R/save_e61.R
> Fix Png scaling
